---
name: devicemapper nightly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 0 3 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  allowed_failures:
    continue-on-error: true
    strategy:
      matrix:
        include:
          # Run "cargo audit" on rust stable. Make it an allowed failure. It
          # should be an advisory and should not gate our development.
          - components: cargo
            toolchain: stable
            task: audit
          # Allowed because a failure may occur after a new Rust stable
          # version is released.
          - components: clippy
            toolchain: stable
            task: clippy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: ${{ matrix.components }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -y install libdevmapper-dev
      - name: Test ${{ matrix.task }} on ${{ matrix.toolchain }} toolchain
        run: make -f Makefile ${{ matrix.task }}

  checks-with-ci-repo:
    continue-on-error: true
    runs-on: ubuntu-18.04
    container:
      image: fedora:33  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies for Fedora
        run: >
          dnf install -y
          clang
          curl
          git
          make
          openssl-devel
          python-requests
          python-semantic_version
      - uses: actions-rs/toolchain@v1
        with:
          components: cargo
          toolchain: 1.52.1  # CURRENT DEVELOPMENT TOOLCHAIN
          override: true
      - name: Check out ci repo
        run: git clone https://github.com/stratis-storage/ci.git
      - name: Compare Fedora versions
        run: ./compare_fedora_versions --manifest-path=../../Cargo.toml
        working-directory: ./ci/dependency_management
